## this is the all-in-one, standalone Discourse Docker container template
##
## After making changes to this file, you MUST rebuild
## /var/discourse/launcher rebuild app
##
## BE *VERY* CAREFUL WHEN EDITING!
## YAML FILES ARE SUPER SUPER SENSITIVE TO MISTAKES IN WHITESPACE OR ALIGNMENT!
## visit http://www.yamllint.com/ to validate this file as needed

templates:
  - "templates/redis.template.yml"
  - "templates/web.template.yml"
  - "templates/web.ratelimited.template.yml"
## Uncomment these two lines if you wish to add Lets Encrypt (https)
  #- "templates/web.ssl.template.yml"
  #- "templates/web.letsencrypt.ssl.template.yml"

## which TCP/IP ports should this container expose?
## If you want Discourse to share a port with another webserver like Apache or nginx,
## see https://meta.discourse.org/t/17247 for details
expose:
  - "80:80"   # http
  - "443:443" # https

params:
  db_default_text_search_config: "pg_catalog.english"

  ## Set db_shared_buffers to a max of 25% of the total memory.
  ## will be set automatically by bootstrap based on detected RAM, or you can override
  #db_shared_buffers: "256MB"

  ## can improve sorting performance, but adds memory usage per-connection
  #db_work_mem: "40MB"

  ## Which Git revision should this container use? (default: tests-passed)
  #version: tests-passed

env:
  DISCOURSE_HOSTNAME: '{{ discourse_hostname }}'
  DISCOURSE_DEVELOPER_EMAILS: '{{ discourse_admin_email }}'

  ## TODO: The SMTP mail server used to validate new accounts and send notifications
  # SMTP ADDRESS, username, and password are required
  # WARNING the char '#' in SMTP password can cause problems!
  DISCOURSE_SMTP_ADDRESS: {{ discourse_smtp_address }}
  DISCOURSE_SMTP_PORT: {{ discourse_smtp_port }}
  DISCOURSE_SMTP_USER_NAME: {{ discourse_smtp_user_name }}
  DISCOURSE_SMTP_PASSWORD: {{ discourse_smtp_password }}
  #DISCOURSE_SMTP_ENABLE_START_TLS: true           # (optional, default true)
  #DISCOURSE_SMTP_DOMAIN: discourse.example.com    # (required by some providers)
  #DISCOURSE_NOTIFICATION_EMAIL: noreply@discourse.example.com    # (address to send notifications from)

  #DISCOURSE_S3_CDN_URL: "{{ discourse_s3_cdn_url }}"

  DISCOURSE_DB_USERNAME: "{{ discourse_db_user }}"
  DISCOURSE_DB_PASSWORD: "{{ discourse_db_password }}"
  DISCOURSE_DB_HOST: "{{ discourse_db_host }}"
  DISCOURSE_DB_NAME: "{{ discourse_db_database }}"
  DISCOURSE_DB_PORT: "{{ discourse_db_port }}"
  DISCOURSE_S3_ACCESS_KEY_ID: "{{ discourse_s3_access_key_id }}"
  DISCOURSE_S3_SECRET_ACCESS_KEY: "{{ discourse_s3_secret_access_key }}"

  DISCOURSE_S3_BUCKET: "{{ discourse_s3_bucket }}"

## The Docker container is stateless; all data is stored in /shared
volumes:
  - volume:
      host: /var/discourse/shared/standalone
      guest: /shared
  - volume:
      host: /var/discourse/shared/standalone/log/var-log
      guest: /var/log

## Plugins go here
## see https://meta.discourse.org/t/19157 for details
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - git clone https://github.com/discourse/docker_manager.git

## Any custom commands to run after building
run:
  - exec: echo "Beginning of custom commands"
  ## If you want to set the 'From' email address for your first registration, uncomment and change:
  ## After getting the first signup email, re-comment the line. It only needs to run once.
  #- exec: rails r "SiteSetting.notification_email='info@unconfigured.discourse.org'"
  - exec: echo "End of custom commands"
